on:
  push

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Mehul_Ved_Resume.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: Mehul_Ved_Resume.pdf
      - name: Get Release
        id: release
        uses: bruceadams/get-release@v1.2.0
      - name: Attach PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: 'Mehul_Ved_Resume.pdf'
          asset_name: 'Mehul_Ved_Resume.pdf'
          asset_content_type: application/pdf  publish-and-release:

  publish
    runs-on: ubuntu-latest
    name: Publish Document to Release
    needs: build_and_release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'Mehul_Ved_Resume.pdf'
      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Get Release
        id: release
        uses: bruceadams/get-release@v1.2.0
      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Attach PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.publish-document.outputs.pdf }}
          asset_name: 'Mehul_Ved_Resume.pdf'
          asset_content_type: application/pdf
jobs:

