on:
  push:
  release:
    types: [publish]

jobs:

  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Mehul_Ved_Resume.tex
      - uses: actions/upload-artifact@v2
        id: build
        with:
          name: PDF
          path: Mehul_Ved_Resume.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
      - name: Get Release
        id: release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Attach PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.path }}
          asset_name: 'Mehul_Ved_Resume.pdf'
          asset_content_type: application/pdf
