name: Build LaTeX document
on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Mehul_Ved_Resume.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: Mehul_Ved_Resume.pdf
      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'Mehul_Ved_Resume.pdf'
          path: 'Mehul_ved_Resume.pdf
        if: startsWith(github.ref, 'refs/tags/')
