name: Build LaTeX document
on: 
  push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Mehul_Ved_Resume.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: Mehul_Ved_Resume.pdf
      - name: Get Release
        id: release
        uses: bruceadams/get-release@v1.2.0
      - name: Attach PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: 'Mehul_Ved_Resume.pdf'
          asset_name: 'Mehul_Ved_Resume.pdf'
          asset_content_type: application/pdf
